export const RiskType = {
    NATURAL_FLOOD: 'NATURAL_FLOOD',
    NATURAL_DROUGHT: 'NATURAL_DROUGHT',
    NATURAL_WIND: 'NATURAL_WIND',
    NATURAL_EARTHQUAKE: 'NATURAL_EARTHQUAKE',
    NATURAL_VOLCANO: 'NATURAL_VOLCANO',
    NATURAL_HEAVY_SNOWFALL: 'NATURAL_HEAVY_SNOWFALL',
    STRIKE: 'STRIKE',
    CIVIL_UNREST: 'CIVIL_UNREST',
    TRADE_EMBARGO: 'TRADE_EMBARGO',
    EPIDEMIC: 'EPIDEMIC',
    WAR: 'WAR',
    PIRACY: 'PIRACY',
    ROUTE_BLOCK: 'ROUTE_BLOCK',
    BLACKOUT: 'BLACKOUT',
    HACKING: 'HACKING',
    SUPPLIER: 'SUPPLIER'
}